import lxml.etree
import lxml.builder
E = lxml.builder.ElementMaker()
ROOT = E.root
DOC = E.doc
intent = E.intent
sender = E.sender
action = E.action
intentname = E.intentname
the_doc = ROOT( 
DOC(intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.BatteryTabActivity'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.BatteryTabActivity'),
action('"com.android.launcher.action.UNINSTALL_SHORTCUT"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.receiver.ShortcutWidget'),
action('"android.settings.SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.receiver.BatteryOptWidgetBig'),
action('"android.settings.SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.powermanager.PowerUsageDetail'),
action('"android.settings.BLUETOOTH_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.ui.DialogHelper'),
action('"android.settings.WIRELESS_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.powermanager.PowerUsageDetail'),
action('"android.settings.WIRELESS_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.BatteryChargingActivity'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.powermanager.PowerUsageDetail'),
action('"android.settings.DISPLAY_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.BatteryTabActivity'),
action('"com.android.launcher.action.INSTALL_SHORTCUT"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.ShortcutWidgetMoreActivityNew'),
action('"android.settings.SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.BatteryTabActivity'),
action('"com.android.launcher.action.UNINSTALL_SHORTCUT"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.NullActivity'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.ShortcutWidgetMoreActivityNew'),
action('"android.settings.WIRELESS_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.receiver.ShortcutWidget'),
action('"android.settings.WIRELESS_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.ShortcutWidgetMoreActivityNew'),
action('"android.settings.LOCATION_SOURCE_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.powermanager.PowerUsageDetail'),
action('"android.settings.WIFI_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.NullActivity'),
action('"android.intent.action.MAIN"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.BatteryTabActivity'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.MsgDeskActivity'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.powermanager.PowerUsageDetail'),
action('"android.settings.WIFI_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.BatteryTabActivity'),
action('"com.android.launcher.action.INSTALL_SHORTCUT"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.ShortcutWidgetMoreActivityNew'),
action('"android.settings.SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.powermanager.PowerUsageDetail'),
action('"android.settings.SECURITY_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.ShortcutWidgetMoreActivityNew'),
action('"android.settings.WIRELESS_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.receiver.ShortcutWidget'),
action('"android.settings.SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.ShortcutWidgetMoreActivityNew'),
action('"android.settings.WIRELESS_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.ShortcutWidgetMoreActivityNew'),
action('"android.settings.SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.MainSettingActivityNew'),
action('"com.android.launcher.action.INSTALL_SHORTCUT"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.onekey.OneKeyActivity'),
action('"com.android.launcher.action.INSTALL_SHORTCUT"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.receiver.BatteryOptWidgetBig'),
action('"android.settings.SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.ShortcutWidgetMoreActivityNew'),
action('"android.settings.LOCATION_SOURCE_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.powermanager.PowerUsageDetail'),
action('"android.settings.WIFI_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.powermanager.PowerUsageDetail'),
action('"android.settings.BLUETOOTH_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.BatteryChargingActivity'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.powermanager.PowerUsageDetail'),
action('"android.settings.WIRELESS_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.ShortcutWidgetMoreActivityNew'),
action('"android.settings.SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.ShortcutWidgetMoreActivityNew'),
action('"android.settings.SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.BatteryChargingActivity'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.MsgDeskActivity'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.MainSettingActivityNew'),
action('"com.android.launcher.action.INSTALL_SHORTCUT"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.NullActivity'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.powermanager.PowerUsageDetail'),
action('"android.settings.WIRELESS_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.receiver.BatteryOptWidgetBig'),
action('"android.settings.SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.receiver.ShortcutWidget'),
action('"android.settings.WIRELESS_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.powermanager.PowerUsageDetail'),
action('"android.settings.SECURITY_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.MsgDeskActivity'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.NullActivity'),
action('"android.intent.action.MAIN"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.ShortcutWidgetMoreActivityNew'),
action('"android.settings.SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.NullActivity'),
action('"android.intent.action.MAIN"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.receiver.BatteryOptWidgetBig'),
action('"android.settings.WIRELESS_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.ui.DialogHelper'),
action('"android.settings.WIRELESS_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.NullActivity'),
action('"android.intent.action.MAIN"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.ShortcutWidgetMoreActivityNew'),
action('"android.settings.SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.NullActivity'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.BatteryTabActivity'),
action('"com.android.launcher.action.INSTALL_SHORTCUT"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.powermanager.PowerUsageDetail'),
action('"android.settings.SECURITY_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.powermanager.PowerUsageDetail'),
action('"android.settings.SECURITY_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.kpref.RingtonePreference'),
action('"android.intent.action.RINGTONE_PICKER"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.kpref.RingtonePreference'),
action('"android.intent.action.RINGTONE_PICKER"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.receiver.ShortcutWidget'),
action('"android.settings.SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.powermanager.PowerUsageDetail'),
action('"android.settings.WIFI_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.onekey.OneKeyActivity'),
action('"com.android.launcher.action.INSTALL_SHORTCUT"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.receiver.BatteryOptWidgetBig'),
action('"android.settings.WIRELESS_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.BatteryTabActivity'),
action('"com.android.launcher.action.UNINSTALL_SHORTCUT"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.kpref.RingtonePreference'),
action('"android.intent.action.RINGTONE_PICKER"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.MainSettingActivityNew'),
action('"com.android.launcher.action.INSTALL_SHORTCUT"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.powermanager.PowerUsageDetail'),
action('"android.settings.BLUETOOTH_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.receiver.ShortcutWidget'),
action('"android.settings.WIRELESS_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.receiver.BatteryOptWidgetBig'),
action('"android.settings.WIRELESS_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.ShortcutWidgetMoreActivityNew'),
action('"android.settings.LOCATION_SOURCE_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.ShortcutWidgetMoreActivityNew'),
action('"android.settings.SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.BatteryTabActivity'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.powermanager.PowerUsageDetail'),
action('"android.settings.BLUETOOTH_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.powermanager.PowerUsageDetail'),
action('"android.settings.DISPLAY_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.ShortcutWidgetMoreActivityNew'),
action('"android.settings.WIRELESS_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.powermanager.PowerUsageDetail'),
action('"android.settings.DISPLAY_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.ui.DialogHelper'),
action('"android.settings.WIRELESS_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.BatteryTabActivity'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.MainSettingActivityNew'),
action('"com.android.launcher.action.INSTALL_SHORTCUT"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.BatteryChargingActivity'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.receiver.ShortcutWidget'),
action('"android.settings.SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.ui.DialogHelper'),
action('"android.settings.WIRELESS_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.MsgDeskActivity'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.receiver.BatteryOptWidgetBig'),
action('"android.settings.WIRELESS_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.kpref.RingtonePreference'),
action('"android.intent.action.RINGTONE_PICKER"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.ShortcutWidgetMoreActivityNew'),
action('"android.settings.LOCATION_SOURCE_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.NullActivity'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.receiver.BatteryOptWidgetBig'),
action('"android.settings.SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.powermanager.PowerUsageDetail'),
action('"android.settings.WIRELESS_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.receiver.ShortcutWidget'),
action('"android.settings.WIRELESS_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.powermanager.PowerUsageDetail'),
action('"android.settings.DISPLAY_SETTINGS"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.BatteryTabActivity'),
action('"com.android.launcher.action.INSTALL_SHORTCUT"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.BatteryTabActivity'),
action('"com.android.launcher.action.UNINSTALL_SHORTCUT"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.onekey.OneKeyActivity'),
action('"com.android.launcher.action.INSTALL_SHORTCUT"'),
),
intent(
intentname('com.ijinshan.kbatterydoctor_en'),
sender('com.ijinshan.kbatterydoctor.onekey.OneKeyActivity'),
action('"com.android.launcher.action.INSTALL_SHORTCUT"'),
),
)
)
print lxml.etree.tostring(the_doc, pretty_print=True)
# Open a file
fo = open('intent.txt', 'wb')
fo.write( lxml.etree.tostring(the_doc, pretty_print=True));
# Close opend file
fo.close()
