import lxml.etree
import lxml.builder
E = lxml.builder.ElementMaker()
ROOT = E.root
DOC = E.doc
component = E.component
packagename = E.packagename
conponentname = E.conponentname
action = E.action
the_doc = ROOT( 
DOC(component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.SplashActivity'),
action('android.intent.action.MAIN'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.ShortcutBatteryInfoActivity'),
action('android.intent.action.MAIN'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.ShortcutWidgetMoreActivityNew'),
action('android.intent.action.MAIN'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.ShortcutWidgetMoreActivity'),
action('android.intent.action.MAIN'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.ShortcutAddActivity'),
action('android.intent.action.MAIN'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.ShortcutAddActivity'),
action('android.intent.action.CREATE_SHORTCUT'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.onekey.OneKeyActivity'),
action('android.intent.action.MAIN'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.onekey.OneKeyShortcutAddActivity'),
action('android.intent.action.MAIN'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.onekey.OneKeyShortcutAddActivity'),
action('android.intent.action.CREATE_SHORTCUT'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.alarmmode.AlarmModeInitReceiver'),
action('android.intent.action.BOOT_COMPLETED'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.alarmmode.AlarmModeInitReceiver'),
action('android.intent.action.TIME_SET'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.alarmmode.AlarmModeInitReceiver'),
action('android.intent.action.TIMEZONE_CHANGED'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.alarmmode.AlarmModeInitReceiver'),
action('android.intent.action.LOCALE_CHANGED'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.receiver.ShortcutWidget'),
action('android.appwidget.action.APPWIDGET_UPDATE'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.receiver.ShortcutWidget'),
action('android.net.wifi.WIFI_STATE_CHANGED'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.receiver.ShortcutWidget'),
action('android.intent.action.PROVIDER_CHANGED'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.receiver.ShortcutWidget'),
action('android.net.conn.CONNECTIVITY_CHANGE'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.receiver.ShortcutWidget'),
action('android.media.RINGER_MODE_CHANGED'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.receiver.ShortcutWidget'),
action('android.media.VOLUME_CHANGED_ACTION'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.receiver.ShortcutWidget'),
action('android.appwidget.action.APPWIDGET_UPDATE'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.receiver.ShortcutWidget'),
action('android.net.wifi.WIFI_STATE_CHANGED'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.receiver.ShortcutWidget'),
action('android.intent.action.PROVIDER_CHANGED'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.receiver.ShortcutWidget'),
action('android.net.conn.CONNECTIVITY_CHANGE'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.receiver.ShortcutWidget'),
action('android.media.RINGER_MODE_CHANGED'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.receiver.ShortcutWidget'),
action('android.media.VOLUME_CHANGED_ACTION'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.receiver.NetChangeedReceiver'),
action('android.net.conn.CONNECTIVITY_CHANGE'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.receiver.AutoStartUpReceiver'),
action('android.intent.action.BOOT_COMPLETED'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.receiver.UserPresentReceiver'),
action('android.intent.action.USER_PRESENT'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.receiver.UserPresentReceiver'),
action('android.intent.action.ACTION_POWER_CONNECTED'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.receiver.UserPresentReceiver'),
action('android.intent.action.ACTION_POWER_DISCONNECTED'),
),
component(
packagename('com.ijinshan.kbatterydoctor_en'),
conponentname('com.ijinshan.kbatterydoctor.tools.cpu.CpuShutdownReceiver'),
action('android.intent.action.ACTION_SHUTDOWN'),
),
)
)
print lxml.etree.tostring(the_doc, pretty_print=True)
# Open a file
fo = open('actions.txt', 'wb')
fo.write( lxml.etree.tostring(the_doc, pretty_print=True));
# Close opend file
fo.close()
