import lxml.etree
import lxml.builder
E = lxml.builder.ElementMaker()
ROOT = E.root
DOC = E.doc
intent = E.intent
sender = E.sender
action = E.action
intentname = E.intentname
the_doc = ROOT( 
DOC(intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.sketchdesk.managers.ShareManager'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.sketchdesk.managers.ShareManager'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.v3.DrawingDeskMainActivity'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.components.InfoPopup'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.components.InfoPopup'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.sketchdesk.managers.ShareManager'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.sketchdesk.managers.ShareManager'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.sketchdesk.managers.ShareManager'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.photodesk.PhotoDeskActivity'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.sketchdesk.managers.ShareManager'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.doodledesk.DoodledeskActivity'),
action('"android.intent.action.PICK"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.photodesk.PhotoDeskActivity'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.components.InfoPopup'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.photodesk.PhotoDeskActivity'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.sketchdesk.managers.ShareManager'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.v3.DrawingDeskMainActivity'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.sketchdesk.managers.ShareManager'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.sketchdesk.managers.FileIOManager'),
action('"android.intent.action.MEDIA_SCANNER_SCAN_FILE"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.market.util.IabHelper'),
action('"com.android.vending.billing.InAppBillingService.BIND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.photodesk.PhotoDeskActivity'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.photodesk.PhotoDeskActivity'),
action('"android.intent.action.PICK"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.components.RateThisApp'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.market.util.IabHelper'),
action('"com.android.vending.billing.InAppBillingService.BIND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.v3.DrawingDeskMainActivity'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.photodesk.PhotoDeskActivity'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.photodesk.PhotoDeskActivity'),
action('"android.media.action.IMAGE_CAPTURE"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.doodledesk.DoodledeskActivity'),
action('"android.intent.action.PICK"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.doodledesk.DoodledeskActivity'),
action('"android.intent.action.PICK"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.sketchdesk.managers.ShareManager'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.v3.DrawingDeskMainActivity'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.v3.DrawingDeskMainActivity'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.components.InfoPopup'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.sketchdesk.managers.FileIOManager'),
action('"android.intent.action.MEDIA_SCANNER_SCAN_FILE"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.components.RateThisApp'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.sketchdesk.managers.ShareManager'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.photodesk.PhotoDeskActivity'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.components.RateThisApp'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.photodesk.PhotoDeskActivity'),
action('"android.intent.action.PICK"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.v3.DrawingDeskMainActivity'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.v3.DrawingDeskMainActivity'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.market.util.IabHelper'),
action('"com.android.vending.billing.InAppBillingService.BIND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.v3.DrawingDeskMainActivity'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.sketchdesk.managers.ShareManager'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.components.InfoPopup'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.sketchdesk.managers.ShareManager'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.photodesk.PhotoDeskActivity'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.market.util.IabHelper'),
action('"com.android.vending.billing.InAppBillingService.BIND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.photodesk.PhotoDeskActivity'),
action('"android.intent.action.PICK"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.v3.DrawingDeskMainActivity'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.v3.DrawingDeskMainActivity'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.components.InfoPopup'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.components.InfoPopup'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.sketchdesk.managers.ShareManager'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.sketchdesk.managers.ShareManager'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.components.RateThisApp'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.photodesk.PhotoDeskActivity'),
action('"android.media.action.IMAGE_CAPTURE"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.sketchdesk.managers.ShareManager'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.v3.DrawingDeskMainActivity'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.sketchdesk.managers.FileIOManager'),
action('"android.intent.action.MEDIA_SCANNER_SCAN_FILE"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.v3.DrawingDeskMainActivity'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.sketchdesk.managers.FileIOManager'),
action('"android.intent.action.MEDIA_SCANNER_SCAN_FILE"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.v3.DrawingDeskMainActivity'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.v3.DrawingDeskMainActivity'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.v3.DrawingDeskMainActivity'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.doodledesk.DoodledeskActivity'),
action('"android.intent.action.PICK"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.photodesk.PhotoDeskActivity'),
action('"android.media.action.IMAGE_CAPTURE"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.photodesk.PhotoDeskActivity'),
action('"android.intent.action.PICK"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.v3.DrawingDeskMainActivity'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.photodesk.PhotoDeskActivity'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.photodesk.PhotoDeskActivity'),
action('"android.media.action.IMAGE_CAPTURE"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.components.InfoPopup'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.axis.drawingdesk.v3'),
sender('com.axis.drawingdesk.sketchdesk.managers.ShareManager'),
action('"android.intent.action.SEND"'),
),
)
)
print lxml.etree.tostring(the_doc, pretty_print=True)
# Open a file
fo = open('intent.txt', 'wb')
fo.write( lxml.etree.tostring(the_doc, pretty_print=True));
# Close opend file
fo.close()
