import lxml.etree
import lxml.builder
E = lxml.builder.ElementMaker()
ROOT = E.root
DOC = E.doc
component = E.component
packagename = E.packagename
conponentname = E.conponentname
action = E.action
the_doc = ROOT( 
DOC(component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.MAIN'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.MEDIA_SEARCH'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.speech.action.VOICE_SEARCH_RESULTS'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.nfc.action.NDEF_DISCOVERED'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.SEARCH'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.MAIN'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.MEDIA_SEARCH'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.speech.action.VOICE_SEARCH_RESULTS'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.nfc.action.NDEF_DISCOVERED'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.SEARCH'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.MAIN'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.MEDIA_SEARCH'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.speech.action.VOICE_SEARCH_RESULTS'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.nfc.action.NDEF_DISCOVERED'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.SEARCH'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.MAIN'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.MEDIA_SEARCH'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.speech.action.VOICE_SEARCH_RESULTS'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.nfc.action.NDEF_DISCOVERED'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.SEARCH'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.MAIN'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.MEDIA_SEARCH'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.speech.action.VOICE_SEARCH_RESULTS'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.nfc.action.NDEF_DISCOVERED'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.SEARCH'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.MAIN'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.MEDIA_SEARCH'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.speech.action.VOICE_SEARCH_RESULTS'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.nfc.action.NDEF_DISCOVERED'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.SEARCH'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.MAIN'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.MEDIA_SEARCH'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.speech.action.VOICE_SEARCH_RESULTS'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.nfc.action.NDEF_DISCOVERED'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.SEARCH'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.MAIN'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.MEDIA_SEARCH'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.speech.action.VOICE_SEARCH_RESULTS'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.nfc.action.NDEF_DISCOVERED'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.Main'),
action('android.intent.action.SEARCH'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.ManageBookmarkActivity'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.ManageBookmarkActivity'),
action('com.android.chrome.ADDBOOKMARK'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.ManageBookmarkActivity'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.ManageBookmarkActivity'),
action('com.android.chrome.ADDBOOKMARK'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.ShortcutActivity'),
action('android.intent.action.CREATE_SHORTCUT'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.sync.ChromeBrowserSyncAdapterService'),
action('android.content.SyncAdapter'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.services.AccountsChangedReceiver'),
action('android.accounts.LOGIN_ACCOUNTS_CHANGED'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.ToSAckedReceiver'),
action('com.android.chrome.TOS_ACKED'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.appwidget.bookmarks.BookmarkThumbnailWidgetProvider'),
action('android.appwidget.action.APPWIDGET_UPDATE'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.snapshot.SnapshotDownloadReceiver'),
action('android.intent.action.DOWNLOAD_COMPLETE'),
),
component(
packagename('com.android.chrome'),
conponentname('com.google.android.apps.chrome.OpenDownloadReceiver'),
action('android.intent.action.DOWNLOAD_NOTIFICATION_CLICKED'),
),
component(
packagename('com.android.chrome'),
conponentname('org.chromium.base.PowerStatusReceiver'),
action('android.intent.action.ACTION_POWER_CONNECTED'),
),
component(
packagename('com.android.chrome'),
conponentname('org.chromium.base.PowerStatusReceiver'),
action('android.intent.action.ACTION_POWER_DISCONNECTED'),
),
)
)
print lxml.etree.tostring(the_doc, pretty_print=True)
# Open a file
fo = open('actions.txt', 'wb')
fo.write( lxml.etree.tostring(the_doc, pretty_print=True));
# Close opend file
fo.close()
