import lxml.etree
import lxml.builder
E = lxml.builder.ElementMaker()
ROOT = E.root
DOC = E.doc
intent = E.intent
sender = E.sender
action = E.action
intentname = E.intentname
the_doc = ROOT( 
DOC(intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.command.Application'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.command.Application'),
action('"com.android.launcher.action.INSTALL_SHORTCUT"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.VideoPlayers'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.Browser'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.Browser'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.Browser'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.command.Application'),
action('"com.android.launcher.action.INSTALL_SHORTCUT"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.command.Application'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.widget.FeedlyWidgetProvider'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.widget.FeedlyWidgetProvider'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.Browser'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.VideoPlayers'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.VideoPlayers'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.ArticleController'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.command.Application'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.command.Application'),
action('"com.android.launcher.action.INSTALL_SHORTCUT"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.widget.FeedlyWidgetProvider'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.command.Application'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.widget.FeedlyWidgetProvider'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.widget.FeedlyWidgetProvider'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.MailSender'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.ArticleController'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.ArticleController'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.widget.FeedlyWidgetProvider'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.VideoPlayers'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.command.Application'),
action('"com.android.launcher.action.INSTALL_SHORTCUT"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.widget.FeedlyWidgetProvider'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.widget.FeedlyWidgetProvider'),
action('"android.intent.action.VIEW"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.MailSender'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.MailSender'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.MailSender'),
action('"android.intent.action.SEND"'),
),
intent(
intentname('com.devhd.feedly'),
sender('com.devhd.feedly.ArticleController'),
action('"android.intent.action.VIEW"'),
),
)
)
print lxml.etree.tostring(the_doc, pretty_print=True)
# Open a file
fo = open('intent.txt', 'wb')
fo.write( lxml.etree.tostring(the_doc, pretty_print=True));
# Close opend file
fo.close()
