import lxml.etree
import lxml.builder
E = lxml.builder.ElementMaker()
ROOT = E.root
DOC = E.doc
component = E.component
packagename = E.packagename
conponentname = E.conponentname
action = E.action
the_doc = ROOT( 
DOC(component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ad.ActivityVideoList'),
action('android.intent.action.MAIN'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ad.ActivityVideoList'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ad.ActivityVideoList'),
action('android.intent.action.SEARCH'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ad.ActivityVideoList'),
action('android.intent.action.MAIN'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ad.ActivityVideoList'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ad.ActivityVideoList'),
action('android.intent.action.SEARCH'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ad.ActivityVideoList'),
action('android.intent.action.MAIN'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ad.ActivityVideoList'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ad.ActivityVideoList'),
action('android.intent.action.SEARCH'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityScreen$WebDelegate'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityScreen$WebDelegate'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityScreen$WebDelegate'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityScreen$WebDelegate'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityScreen$WebDelegate'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityScreen$WebDelegate'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityScreen$WebDelegate'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityScreen$WebDelegate'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityScreen$WebDelegate'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityScreen$LocalAudioDelegate'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityScreen$LocalAudioDelegate'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityScreen$LocalAudioDelegate'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityScreen$LocalAudioDelegate'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityScreen$WebAudioDelegate'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityScreen$WebAudioDelegate'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityScreen$WebAudioDelegate'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityScreen$WebAudioDelegate'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityScreen$WebAudioDelegate'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityScreen$WebAudioDelegate'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityScreen$WebAudioDelegate'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityScreen$WebAudioDelegate'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityScreen$WebAudioDelegate'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ad.ActivityScreen'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ad.ActivityScreen'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ad.ActivityScreen'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ad.ActivityScreen'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ad.ActivityScreen'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ad.ActivityScreen'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ad.ActivityScreen'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ad.ActivityScreen'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ad.ActivityScreen'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityPreferences'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityScanRootSelector'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityVideoFile'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityAbout'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityMessenger'),
action('android.intent.action.VIEW'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityVideoList$AudioEventReceiver'),
action('android.intent.action.MEDIA_BUTTON'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.ActivityScreen$AudioEventReceiver'),
action('android.intent.action.MEDIA_BUTTON'),
),
component(
packagename('com.mxtech.videoplayer.ad'),
conponentname('com.mxtech.videoplayer.service.PlayService$AudioEventReceiver'),
action('android.intent.action.MEDIA_BUTTON'),
),
)
)
print lxml.etree.tostring(the_doc, pretty_print=True)
# Open a file
fo = open('actions.txt', 'wb')
fo.write( lxml.etree.tostring(the_doc, pretty_print=True));
# Close opend file
fo.close()
